/**
 * Servicio MailSend Kallsonys
 * Servicio para el envio de correos
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Status de respuesta.
 */
export interface StatusType { 
    /**
     * Codigo de status.
     */
    statusCode?: number;
    /**
     * Descripcion de estatus.
     */
    statusDesc?: string;
}
