/**
 * Servicio TarjetasCredito Kallsonys
 * Servicio para la gestión de tarjetas de credito en OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { TarjetaCredito } from '../model/tarjetaCredito';
import { TarjetaCreditoRsType } from '../model/tarjetaCreditoRsType';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TarjetaCreditoService {
    protected basePath = 'http://10.39.1.156:8210/esb-skynet';
    // protected basePath = 'http://10.39.1.149:8569/OMS/TarjetaCredito/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Actualizar una Tarjeta de Credito
     * 
     * @param headerRq Cabecera estándar
     * @param serviceID servKall4
     * @param tarjetaDeCredito Tarjeta de Credito a actualizar
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public actualizarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'body', reportProgress?: boolean): Observable<TarjetaCreditoRsType>;
    public actualizarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TarjetaCreditoRsType>>;
    public actualizarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TarjetaCreditoRsType>>;
    public actualizarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (headerRq === null || headerRq === undefined) {
            throw new Error('Required parameter headerRq was null or undefined when calling actualizarTarjetaDeCredito.');
        }

        if (serviceID === null || serviceID === undefined) {
            throw new Error('Required parameter serviceID was null or undefined when calling actualizarTarjetaDeCredito.');
        }

        if (tarjetaDeCredito === null || tarjetaDeCredito === undefined) {
            throw new Error('Required parameter tarjetaDeCredito was null or undefined when calling actualizarTarjetaDeCredito.');
        }

        let headers = this.defaultHeaders;
        if (headerRq !== undefined && headerRq !== null) {
            headers = headers.set('headerRq', String(headerRq));
        }
        if (serviceID !== undefined && serviceID !== null) {
            headers = headers.set('serviceID', String(serviceID));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<TarjetaCreditoRsType>(`${this.basePath}/tarjetaDeCredito`,
            tarjetaDeCredito,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Consultar Tarjeta de Credito por Cliente
     * Retorna una tarjeta de credito
     * @param headerRq Cabecera estándar
     * @param serviceID servKall4
     * @param idCliente idCliente
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public consultarTarjetaDeCreditoPorCliente(headerRq: string, serviceID: string, idCliente: string, observe?: 'body', reportProgress?: boolean): Observable<TarjetaCreditoRsType>;
    public consultarTarjetaDeCreditoPorCliente(headerRq: string, serviceID: string, idCliente: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TarjetaCreditoRsType>>;
    public consultarTarjetaDeCreditoPorCliente(headerRq: string, serviceID: string, idCliente: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TarjetaCreditoRsType>>;
    public consultarTarjetaDeCreditoPorCliente(headerRq: string, serviceID: string, idCliente: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (headerRq === null || headerRq === undefined) {
            throw new Error('Required parameter headerRq was null or undefined when calling consultarTarjetaDeCreditoPorCliente.');
        }

        if (serviceID === null || serviceID === undefined) {
            throw new Error('Required parameter serviceID was null or undefined when calling consultarTarjetaDeCreditoPorCliente.');
        }

        if (idCliente === null || idCliente === undefined) {
            throw new Error('Required parameter idCliente was null or undefined when calling consultarTarjetaDeCreditoPorCliente.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCliente !== undefined && idCliente !== null) {
            queryParameters = queryParameters.set('idCliente', <any>idCliente);
        }

        let headers = this.defaultHeaders;
        if (headerRq !== undefined && headerRq !== null) {
            headers = headers.set('headerRq', String(headerRq));
        }
        if (serviceID !== undefined && serviceID !== null) {
            headers = headers.set('serviceID', String(serviceID));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<TarjetaCreditoRsType>(`${this.basePath}/tarjetaDeCredito/consultarPorCliente`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Eliminar una Tarjeta de Credito
     * 
     * @param headerRq Cabecera estándar
     * @param serviceID servKall4
     * @param tarjetaDeCredito Tarjeta de Credito a eliminar
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eliminarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'body', reportProgress?: boolean): Observable<TarjetaCreditoRsType>;
    public eliminarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TarjetaCreditoRsType>>;
    public eliminarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TarjetaCreditoRsType>>;
    public eliminarTarjetaDeCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (headerRq === null || headerRq === undefined) {
            throw new Error('Required parameter headerRq was null or undefined when calling eliminarTarjetaDeCredito.');
        }

        if (serviceID === null || serviceID === undefined) {
            throw new Error('Required parameter serviceID was null or undefined when calling eliminarTarjetaDeCredito.');
        }

        if (tarjetaDeCredito === null || tarjetaDeCredito === undefined) {
            throw new Error('Required parameter tarjetaDeCredito was null or undefined when calling eliminarTarjetaDeCredito.');
        }

        let headers = this.defaultHeaders;
        if (headerRq !== undefined && headerRq !== null) {
            headers = headers.set('headerRq', String(headerRq));
        }
        if (serviceID !== undefined && serviceID !== null) {
            headers = headers.set('serviceID', String(serviceID));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.delete<TarjetaCreditoRsType>(`${this.basePath}/tarjetaDeCredito`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Registrar una Tarjeta de Credito
     * 
     * @param headerRq Cabecera estándar
     * @param serviceID servKall4
     * @param tarjetaDeCredito Tarjeta de Credito a registrar
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registrarTarjetaCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'body', reportProgress?: boolean): Observable<TarjetaCreditoRsType>;
    public registrarTarjetaCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TarjetaCreditoRsType>>;
    public registrarTarjetaCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TarjetaCreditoRsType>>;
    public registrarTarjetaCredito(headerRq: string, serviceID: string, tarjetaDeCredito: TarjetaCredito, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (headerRq === null || headerRq === undefined) {
            throw new Error('Required parameter headerRq was null or undefined when calling registrarTarjetaCredito.');
        }

        if (serviceID === null || serviceID === undefined) {
            throw new Error('Required parameter serviceID was null or undefined when calling registrarTarjetaCredito.');
        }

        if (tarjetaDeCredito === null || tarjetaDeCredito === undefined) {
            throw new Error('Required parameter tarjetaDeCredito was null or undefined when calling registrarTarjetaCredito.');
        }

        let headers = this.defaultHeaders;
        if (headerRq !== undefined && headerRq !== null) {
            headers = headers.set('headerRq', String(headerRq));
        }
        if (serviceID !== undefined && serviceID !== null) {
            headers = headers.set('serviceID', String(serviceID));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<TarjetaCreditoRsType>(`${this.basePath}/tarjetaDeCredito`,
            tarjetaDeCredito,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
