/**
 * Servicio TarjetasCredito Kallsonys
 * Servicio para la gestión de tarjetas de credito en OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusType } from './statusType';
import { TarjetaCredito } from './tarjetaCredito';


/**
 * Respuesta genérica.
 */
export interface TarjetaCreditoRsType { 
    status?: StatusType;
    datosBasicos?: TarjetaCredito[];
}
